name: fire_flutter
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  file_picker: ^5.3.3
  dotted_border: ^2.0.0+3
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  toast: ^0.3.0
  flutter_slidable: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  google_maps_flutter: ^2.4.0
  firebase_auth: ^4.7.2
  get: ^4.6.5
  google_sign_in: ^6.1.4
  country_picker: ^2.0.20
  pinput: ^3.0.0
  flutter_easyloading: ^3.0.5
  razorpay_flutter: ^1.3.5
  image_picker: ^1.0.2
  firebase_app_check: ^0.1.5+2
  image_cropper: ^5.0.0
  path: ^1.8.3
  double_back_to_close_app: ^2.1.0
  firebase_messaging: ^14.6.7
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/kik.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logo_forground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Jealous-amico.png
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
